### PR TITLE
Added FREEBOX plugin

### PR DESCRIPTION
**Pull request by KayJay7**
This adds a plugin to pull devices and names from a Freebox gateway, using their API. The details are in the README.

Our use-case of this plugin is for the Italian re-branding of the freebox, the "Iliadbox".

Support for the Iliadbox requires adding an [extra ssl certificate](https://github.com/fstercq/freepybox/commit/3585e973cc12afa9dad2589cd9068062a3e3f60e). There are a number of ways to handle this, like mounting the file with the certificate, or getting it merged upstream.
In the meantime, I made no mention of the Iliadbox in the README.

Co-authored-by: @Lucide

### CODE REVIEW

**Comment by KayJay7** [comment]
The API also offer a lot of information about devices and IPs that are not online at the moment, but including devices that are not online in the scan will make them show as online, regardless of the `last seen` field. Is there a way to get that past data in the database?

There is the `NEWDEV_dev_PresentLastScan` setting in the New Devices plugin that looks related, but I don't know what it does.

**Comment by Lucide** [comment]
Hello, some considerations on [foreign-sub/aiofreepybox](https://github.com/foreign-sub/aiofreepybox), the python library that implements the freebox API:
The library is a fork of [hacf-fr/freebox-api](https://github.com/hacf-fr/freebox-api). I've chosen it because it supports API connections through LAN, thus it can work without an internet connection.
The author implemented a quite sophisticated (and perhaps a bit over-engineered) mechanism for auto-discovery, and protocol selection. By default, the library will always still attempt a remote SSL connection (over internet) first, and fall back to a local http connection in case of failure (if the conditions mentioned in the readme are met). SSL on the freebox works only from the public address, so it requires internet connection.

However, the way the library is implemented does not allow certificate validation failures (even with `_DEFAULT_SSL=False`), so it requires appending the "iliad" certificate to `freebox_certificates.pem` at container build-time (or with user mount instructions). This is what we are currently doing in our setup for SSL.

We could attempt a pull request on the library but it seems abandoned. In the future the active fork might catch up in features.

**Comment by jokob-sk** [comment]
Amazing collab @KayJay7 @Lucide 🙏 is it good to be merged? Do we need to add some notes regarding the certificate setup in the README?

**Comment by KayJay7** [comment]
I have pushed some more commits. One is just a fix for a missing dependency in the dockerfile.
The other two are one to add the certificate and the other for the documentation.
We have opted for appending the certificate with a command in the dockerfile.

Now it's good to merge

**Comment by jokob-sk** [comment]
@KayJay7 Sorry, forgot to answer your question:

> Question: the API offers historical information about devices and IPs that are not online at the moment, but were at one point.

> I see no way to make use of this; as far as I understand, if we report offline devices they will appear as online, and the last seen field seems ignored. Is there a way to get that past data in the database?

> There is the NEWDEV_dev_PresentLastScan setting in the New Devices plugin that looks related, but I'm not sure.

Currently, all devices passed thru the CurrentScan table will be reported as online. Although possible, I prefer not to write directly to the DB in the plugins to keep the flow and logic clean. 

It's something on my radar to improve in future - to figure out the import of "offline" devices, without the need to go thru the CurrentScan table in a more scalable way - to be incorporated into the plugin framework. Happy to hear ideas as well.

**Comment by jokob-sk** [comment]
I might move the certificate in a separate file in the future, but I think this is good to go for now - let's see how much teh image grows due to the addition of `git` though

**Comment by Lucide** [comment]
As an alternative to git, we could use
```
pip install 'aiofreepybox@https://github.com/foreign-sub/aiofreepybox/archive/refs/heads/afpbx-next.zip
```
Installation from source archive file.

**Pull request merged**
