### PR TITLE
chore: fixed mtscan and Dockerfile

### PR DESCRIPTION
**Pull request by elraro**
Trying to fix the mtscan plugin, but I had some questions about NetAlertX.

@jokob-sk check mail!

### CODE REVIEW

**Comment by jokob-sk** [comment]
Hey @elraro - I couldn't find any email, can you resend it to netalert@gmail.com or jokob.sk@gmail.com?

**Comment by elraro** [comment]
@jokob-sk done! Check spam! (i think google is marking me as spam, idk why :( i should speak with support).

**Comment by jokob-sk** [comment]
Thanks, found it and replied! :)

**Comment by jokob-sk** [comment]
hey @elraro do you think I can release a new version with the plugin being as it is or should I hold off until this PR is merged?

**Comment by elraro** [comment]
hi @jokob-sk ! Sorry, I am very busy at work :) the plugin works, but I think is wrong, because the plugin only obtains the devices from Mikrotik that are in the list of NetAlertX, not the full list.

let me write you tomorrow in the morning with my questions about how NetAlertX works and then you can decide!

**Comment by jokob-sk** [comment]
Thanks @elraro ! Not sure if @lookflying has time to collaborate on this. I also created a Discord chat if you prefer s space with DMs etc: https://discord.gg/UQnnHNYV

**Comment by lookflying** [comment]
> hi @jokob-sk ! Sorry, I am very busy at work :) the plugin works, but I think is wrong, because the plugin only obtains the devices from Mikrotik that are in the list of NetAlertX, not the full list.
> 
> let me write you tomorrow in the morning with my questions about how NetAlertX works and then you can decide!

I initially defined this plugin as a name resolver, so it only updates the names of existing devices. I think it would be fine to change it to apply to all devices in the leases as well. However, I suggest also changing the plugin type to 'device scanner'.

**Comment by elraro** [comment]
Hi jokob! Yes, this night! Sorry for the late!

**Comment by elraro** [comment]
@jokob-sk done!

**Comment by jokob-sk** [comment]
Amazing - thanks a lot!

**Pull request merged**
